stages: 
  load_data:
    cmd: python src/dataIngestion.py --config=config/config.yaml
    deps:
      - src/dataIngestion.py
      - src/utils/all_utils.py
      - config/config.yaml

    outs:
      - artifacts/raw_local_dir/data.csv
  transformation:
      cmd: python src/dataTransformation.py --config=config/config.yaml
      deps:
        - src/dataIngestion.py
        - src/utils/all_utils.py
        - config/config.yaml

      outs:
        - artifacts/transform_local_dir/transformed_data.csv
    