stages: 
  load_data:
    cmd: python src/dataIngestion.py --config=config/config.yaml
    deps:
      - src/dataIngestion.py
      - src/utils/all_utils.py
      - config/config.yaml

    outs:
      - artifacts/raw_local_dir/data.csv
  transformation:
      cmd: python src/dataTransformation.py --config=config/config.yaml
      deps:
        - src/dataTransformation.py
        - src/utils/all_utils.py
        - config/config.yaml
      outs:
        - artifacts/transform_local_dir/transformed_data.csv
  split_data:
      cmd: python src/splitData.py --config=config/config.yaml --params=params.yaml
      deps:
        - src/splitData.py
        - src/utils/all_utils.py
        - config/config.yaml
        - artifacts/raw_local_dir/data.csv
        - src/dataTransformation.py
        - src/dataIngestion.py
      params:
        - base.random_state
        - base.test_size
      outs:
        - artifacts/split_data_dir/train.csv
        - artifacts/split_data_dir/test.csv