data_source: https://raw.githubusercontent.com/Jvdboss7/Dataset/e88057fece8f5493fc9ac3a4495f555338d9a17a/backorder.csv
artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  transform_data_dir: transform_local_dir
  transform_data_file: transformed_data.csv 

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv
